/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/my-tutor`; params?: Router.UnknownInputParams; } | { pathname: `/tutors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/class/[classId]`, params: Router.UnknownInputParams & { classId: string | number; } } | { pathname: `/tutor/[tutorId]`, params: Router.UnknownInputParams & { tutorId: string | number; } } | { pathname: `/worksheet/[worksheetId]`, params: Router.UnknownInputParams & { worksheetId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/my-tutor`; params?: Router.UnknownOutputParams; } | { pathname: `/tutors`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/classes` | `/classes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/class/[classId]`, params: Router.UnknownOutputParams & { classId: string; } } | { pathname: `/tutor/[tutorId]`, params: Router.UnknownOutputParams & { tutorId: string; } } | { pathname: `/worksheet/[worksheetId]`, params: Router.UnknownOutputParams & { worksheetId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/attendance${`?${string}` | `#${string}` | ''}` | `/my-tutor${`?${string}` | `#${string}` | ''}` | `/tutors${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/classes${`?${string}` | `#${string}` | ''}` | `/classes${`?${string}` | `#${string}` | ''}` | `${'/(student)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/my-tutor`; params?: Router.UnknownInputParams; } | { pathname: `/tutors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | `/class/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tutor/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/worksheet/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/class/[classId]`, params: Router.UnknownInputParams & { classId: string | number; } } | { pathname: `/tutor/[tutorId]`, params: Router.UnknownInputParams & { tutorId: string | number; } } | { pathname: `/worksheet/[worksheetId]`, params: Router.UnknownInputParams & { worksheetId: string | number; } };
    }
  }
}
